package top.feng.model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Newslogs extends BaseNewslogs<Newslogs> {
	public static final Newslogs dao = new Newslogs().dao();
}
