package top.feng.model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Newsmodules extends BaseNewsmodules<Newsmodules> {
	public static final Newsmodules dao = new Newsmodules().dao();
}
