package top.feng.model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Recommendations extends BaseRecommendations<Recommendations> {
	public static final Recommendations dao = new Recommendations().dao();
}
