package top.feng.model;

import top.feng.model.base.BaseNewsTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsTemp extends BaseNewsTemp<NewsTemp> {
	public static final NewsTemp dao = new NewsTemp().dao();
}
